access_rights:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: DEEPN_ACCESS_RIGHTS
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: access_type
        AttributeType: S
      - AttributeName: shared_by
        AttributeType: S
      - AttributeName: task_id
        AttributeType: S
    KeySchema:
      - AttributeName: task_id
        KeyType: HASH
      - AttributeName: user_id
        KeyType: RANGE
    GlobalSecondaryIndexes:
      - IndexName: UserId
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: UserID_AccessType
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: access_type
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: UserID_SharedBy
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: shared_by
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    BillingMode: PAY_PER_REQUEST
    SSESpecification:
      SSEEnabled: true
