tasks:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: DEEPN_TASKS
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: type
        AttributeType: S
      - AttributeName: date
        AttributeType: S
      - AttributeName: status
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: UserId
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: Date
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: Status
        KeySchema:
          - AttributeName: status
            KeyType: HASH
        Projection:
          ProjectionType: ALL
      - IndexName: Type
        KeySchema:
          - AttributeName: type
            KeyType: HASH
        Projection:
          ProjectionType: ALL
    BillingMode: PAY_PER_REQUEST
    SSESpecification:
      SSEEnabled: true
